#!/usr/bin/env node
/**
 * generate-readme.js
 *
 * Scans challenges/ directory, reads each challenge.json,
 * and regenerates the challenge table in README.md between:
 *
 *   <!-- CHALLENGES_START -->
 *   ...auto-generated content...
 *   <!-- CHALLENGES_END -->
 *
 * Run manually:  node scripts/generate-readme.js
 * Or via CI:     triggered automatically on push by GitHub Actions
 */

import { readdirSync, readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const ROOT          = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHALLENGES_DIR = join(ROOT, 'challenges');
const README_PATH   = join(ROOT, 'README.md');

// ---------------------------------------------------------------------------
// 1. Read all challenges
// ---------------------------------------------------------------------------
const challenges = readdirSync(CHALLENGES_DIR, { withFileTypes: true })
  .filter(e => e.isDirectory())
  .flatMap(folder => {
    try {
      const config = JSON.parse(
        readFileSync(join(CHALLENGES_DIR, folder.name, 'challenge.json'), 'utf8')
      );
      return [{ ...config, slug: folder.name }];
    } catch {
      console.warn(`  ⚠ Skipping "${folder.name}": missing or invalid challenge.json`);
      return [];
    }
  })
  .sort((a, b) => a.id - b.id);

// ---------------------------------------------------------------------------
// 2. Build the markdown section
// ---------------------------------------------------------------------------
const date = new Date().toISOString().split('T')[0];

const rows = challenges.map(c => {
  const fileCount = c.challengeFiles?.length ?? 0;
  const files     = fileCount === 1 ? '1 file' : `${fileCount} files`;
  return `| ${c.id} | **${c.name}** | \`${c.slug}\` | ${c.description} | ${files} |`;
});

const section = [
  `## 📋 Challenges (${challenges.length} total)`,
  '',
  '| # | Name | Slug | Description | Downloads |',
  '|---|------|------|-------------|-----------|',
  ...rows,
  '',
  `*Last updated: ${date} — auto-generated by [GitHub Actions](.github/workflows/update-readme.yml)*`,
].join('\n');

// ---------------------------------------------------------------------------
// 3. Replace between markers in README.md
// ---------------------------------------------------------------------------
const START_MARKER = '<!-- CHALLENGES_START -->';
const END_MARKER   = '<!-- CHALLENGES_END -->';

let readme = readFileSync(README_PATH, 'utf8');

const startIdx = readme.indexOf(START_MARKER);
const endIdx   = readme.indexOf(END_MARKER);

if (startIdx === -1 || endIdx === -1) {
  console.error('✗ Markers not found in README.md');
  console.error(`  Add "${START_MARKER}" and "${END_MARKER}" to README.md`);
  process.exit(1);
}

readme =
  readme.slice(0, startIdx + START_MARKER.length) +
  '\n' + section + '\n' +
  readme.slice(endIdx);

writeFileSync(README_PATH, readme, 'utf8');

console.log(`✓ README.md updated with ${challenges.length} challenge(s):`);
challenges.forEach(c => console.log(`  [${c.id}] ${c.slug} — ${c.name}`));
